Repository geirolz/advxml, pull requests merged in 2021-07, with the labels that each got.

#244 Add support for Scala 3
  .github/workflows/cicd.yml
  .mergify.yml
  .scalafmt.conf
  README.md
  build.sbt
  modules/core/src/main/scala/advxml/core/TypeInequalities.scala
  modules/core/src/main/scala/advxml/core/data/Converter.scala
  modules/core/src/main/scala/advxml/core/data/Value.scala
  modules/core/src/main/scala/advxml/core/transform/XmlZoom.scala
  modules/core/src/main/scala/advxml/core/utils/XmlUtils.scala
  modules/core/src/main/scala/advxml/instances/AllDataInstances.scala
  modules/core/src/main/scala/advxml/instances/AllTransforInstances.scala
  modules/core/src/main/scala/advxml/syntax/AllTransformSyntax.scala
  modules/core/src/test/scala-2/advxml/instances/ConvertersAssertsUtils.scala
  modules/core/src/test/scala-3/advxml/instances/ConvertersAssertsUtils.scala
  modules/core/src/test/scala/advxml/core/TypeInequalitiesTest.scala
  modules/core/src/test/scala/advxml/core/data/AggregatedExceptionTest.scala
  modules/core/src/test/scala/advxml/core/transform/XmlTransformationSpec.scala
  modules/core/src/test/scala/advxml/instances/DataConvertInstancesTest.scala
  modules/core/src/test/scala/advxml/instances/TransformXmlModifierInstancesTest.scala
  modules/core/src/test/scala/advxml/syntax/DataConvertFullSyntaxTest.scala
  project/Dependencies.scala
Labels: enhancement

#246 Update Docs
  .github/workflows/GPG_Tutorial.md
  .github/workflows/setup-release_keys_guide.md
  README.md
Labels: documentation

#247 Refactoring conversion and rename Ex with Throw
  modules/core/docs/Convert.md
  modules/core/docs/Value.md
  modules/core/src/main/scala/advxml/core/AppExOrEu.scala
  modules/core/src/main/scala/advxml/core/ApplicativeThrowOrEu.scala
  modules/core/src/main/scala/advxml/core/MonadEx.scala
  modules/core/src/main/scala/advxml/core/TypeInequalities.scala
  modules/core/src/main/scala/advxml/core/data/Converter.scala
  modules/core/src/main/scala/advxml/core/data/ValidatedNelThrow.scala
  modules/core/src/main/scala/advxml/core/data/ValidationRule.scala
  modules/core/src/main/scala/advxml/core/data/Value.scala
  modules/core/src/main/scala/advxml/core/data/ValueExtractor.scala
  modules/core/src/main/scala/advxml/core/data/package.scala
  modules/core/src/main/scala/advxml/core/package.scala
  modules/core/src/main/scala/advxml/core/transform/AbstractRule.scala
  modules/core/src/main/scala/advxml/core/transform/XmlModifier.scala
  modules/core/src/main/scala/advxml/core/transform/XmlZoom.scala
  modules/core/src/main/scala/advxml/instances/AllDataInstances.scala
  modules/core/src/main/scala/advxml/instances/AllTransforInstances.scala
  modules/core/src/main/scala/advxml/syntax/AllDataSyntax.scala
  modules/core/src/main/scala/advxml/syntax/AllTransformSyntax.scala
  modules/core/src/test/scala-2/advxml/instances/ConvertersAssertsUtils.scala
  modules/core/src/test/scala-3/advxml/instances/ConvertersAssertsUtils.scala
  modules/core/src/test/scala/advxml/core/AppExOrEuTest.scala
  modules/core/src/test/scala/advxml/core/ApplicativeThrowOrEuTest.scala
  modules/core/src/test/scala/advxml/core/MonadExUtilsTest.scala
  modules/core/src/test/scala/advxml/core/data/ConverterTest.scala
  modules/core/src/test/scala/advxml/core/data/ValidateExTest.scala
  modules/core/src/test/scala/advxml/core/data/ValidateThrowTest.scala
  modules/core/src/test/scala/advxml/core/data/ValidatedConverterTest.scala
  modules/core/src/test/scala/advxml/core/transform/XmlContentZoomTest.scala
  modules/core/src/test/scala/advxml/instances/DataConvertInstancesTest.scala
  modules/core/src/test/scala/advxml/syntax/DataConvertFullSyntaxTest.scala
  modules/core/src/test/scala/advxml/syntax/DataConvertSyntaxTest.scala
  modules/core/src/test/scala/advxml/syntax/ValidatedSyntaxTest.scala
Labels: documentation, enhancement
