Repository geirolz/advxml, pull requests merged in 2021-04, with the labels that each got.

#199 SetAttrs should take Elem as argument
  .gitignore
  modules/core/src/main/scala/advxml/instances/AllTransforInstances.scala
  modules/core/src/test/scala/advxml/core/transform/XmlTransformationSpec.scala
  modules/core/src/test/scala/advxml/syntax/TransformModifiersTest.scala
  modules/core/src/test/scala/advxml/syntax/TransformXmlRuleSyntaxTest.scala
Labels: enhancement, nice to have

#203 Add contributors in README
  README.md
Labels: documentation

#211 Fix scala doc generation
  build.sbt
Labels: bug, documentation
